import { renderStation } from '@/lib/stations';
import { config, repoFull } from '@/lib/config';
import {
  comment, commitChanges, ensureSandbox, finishDevBranch, getIssue, latestReview, prChangedPaths, prepareDevPr,
  prepareRepo, readChanges, readResult, runAgentSlice, runVerify, setLabels, stopSandbox, upsertPr,
} from './steps';

/**
 * Spec, Implement, or a revision of Implement after review (`revision`). All runs on an issue share its sandbox,
 * which is stopped (not deleted) at the end of each run and deleted when the PR is merged (workflows/cleanup.ts).
 */
export async function codingStationWorkflow(input: { station: 'spec' | 'implement'; issue: number; runId: string; revision?: boolean }) {
  'use workflow';
  const { station: name, issue, runId, revision } = input;
  const branch = config.branch(issue);
  const issueData = await getIssue(issue);
  if (issueData.labels.includes(config.labels.running)) return; // another run is in progress
  await setLabels(issue, [config.labels.running], [config.labels.blocked, config.labels.changesRequested]);

  let sandboxId: string | undefined;
  try {
    sandboxId = await ensureSandbox(issue);
    const { baseSha } = await prepareRepo(sandboxId, branch);
    // Dev pushes its branch itself, so its PR must exist (as a draft: pushes to a draft don't start Review).
    const dev = name === 'implement' ? { pr: await prepareDevPr(issue, branch, issueData.title) } : undefined;
    const review = revision && dev ? await latestReview(dev.pr) : '';
    const station = renderStation(revision ? 'revise' : name, {
      repoFull, issue, branch, pr: dev?.pr ?? '', review, issueTitle: issueData.title, issueBody: issueData.body,
    });

    let prompt = station.prompt;
    let verify: { ok: boolean; output: string } | undefined;
    for (let round = 0; round <= (station.maxFixRounds ?? 0); round++) {
      let slice = await runAgentSlice({ sandboxId, sessionId: `${runId}-${round}`, prompt, dev });
      while (!slice.done) {
        slice = await runAgentSlice({ sandboxId, sessionId: `${runId}-${round}`, continuation: slice.continuation, dev });
      }
      if (!station.verify) break;
      verify = await runVerify(sandboxId, station.verify); // the orchestrator checks; it doesn't trust the agent
      if (verify.ok) break;
      prompt = `The verification command \`${station.verify}\` failed. Output (tail):\n\n\`\`\`\n${verify.output}\n\`\`\`\n\nFix the code, run it again, and push. Update .factory/result.json.`;
    }

    const result = await readResult(sandboxId);
    const message = `${name === 'spec' ? 'docs(specs)' : 'feat'}: ${issueData.title} (#${issue})\n\nGenerated by the software factory (${runId}).`;

    if (dev) {
      // Dev already pushed; push whatever it left, then check the PR's whole diff, since nothing filtered its pushes.
      const { headSha } = await finishDevBranch(sandboxId, dev, message);
      const protectedHits = (await prChangedPaths(dev.pr)).filter((p) => config.protectedPaths.some((r) => r.test(p)));
      if (protectedHits.length > 0) {
        await comment(issue, `Implementation is blocked: the branch changes protected paths (${protectedHits.map((p) => `\`${p}\``).join(', ')}). See draft PR #${dev.pr}.`);
        await setLabels(issue, [config.labels.blocked]);
        return;
      }
      // A first implementation must change something. A revision may rightly change nothing: it goes back to Review.
      if (headSha === baseSha && !revision) {
        await comment(issue, `The implement station finished without changing any file.\n\n${result.summary ?? ''}`);
        await setLabels(issue, [config.labels.blocked]);
        return;
      }
    } else {
      const changes = await readChanges(sandboxId);
      if (changes.length === 0) {
        await comment(issue, `The ${name} station finished without changing any file.\n\n${result.summary ?? ''}`);
        await setLabels(issue, [config.labels.blocked]);
        return;
      }
      await commitChanges({ branch, baseSha, changes, allowedPaths: station.allowedPaths?.map((p) => p.replace(/\/?$/, '/')), message });
    }
    const pr = await upsertPr(name, issue, branch, issueData.title, result, verify);

    if (name === 'spec') {
      await comment(issue, `Specs are ready for review in #${pr}. A maintainer applies \`${config.labels.readyToImplement}\` to start the implementation.`);
    } else if (verify && !verify.ok) {
      await comment(issue, `Implementation is blocked: verification still fails after the fix rounds. See draft PR #${pr}.`);
      await setLabels(issue, [config.labels.blocked]);
    }
  } finally {
    if (sandboxId) await stopSandbox(sandboxId);
    await setLabels(issue, [], [config.labels.running]);
  }
}
