import { renderStation } from '@/lib/stations';
import { config, repoFull } from '@/lib/config';
import type { SandboxStation } from '@/core/types';
import {
  comment, commitStationChanges, ensureSandbox, finishDevBranch, getIssue, latestReview, prepareDevPr, prepareRepo,
  readChanges, readResult, readyForReview, runAgentSlice, runVerify, setLabels, stopSandbox, upsertPr,
} from './steps';

/**
 * Spec, Implement, or a revision of Implement after review (`revision`). All runs on an issue share its sandbox,
 * which is stopped (not deleted) at the end of each run and deleted when the PR is merged (workflows/cleanup.ts).
 * What each station may reach, change and decide is in core/rules/*.cedar.
 */
export async function codingStationWorkflow(input: { station: 'spec' | 'implement'; issue: number; runId: string; revision?: boolean }) {
  'use workflow';
  const { station: name, issue, runId, revision } = input;
  const station: SandboxStation = revision ? 'revise' : name;
  const branch = config.branch(issue);
  const issueData = await getIssue(issue);
  if (issueData.labels.includes(config.labels.running)) return; // another run is in progress
  await setLabels(issue, [config.labels.running], [config.labels.blocked, config.labels.changesRequested]);

  const blocked = async (why: string) => {
    await comment(issue, why);
    await setLabels(issue, [config.labels.blocked]);
  };

  let sandboxId: string | undefined;
  try {
    sandboxId = await ensureSandbox(issue);
    const { baseSha } = await prepareRepo(sandboxId, branch);
    // Dev pushes its branch itself, so its PR must exist (as a draft: pushes to a draft don't start Review).
    const dev = name === 'implement' ? { pr: await prepareDevPr(issue, branch, issueData.title) } : undefined;
    const review = revision && dev ? await latestReview(dev.pr) : '';
    const template = renderStation(station, {
      repoFull, issue, branch, pr: dev?.pr ?? '', review, issueTitle: issueData.title, issueBody: issueData.body,
    });

    let prompt = template.prompt;
    let verify: { ok: boolean; output: string } | undefined;
    for (let round = 0; round <= (template.maxFixRounds ?? 0); round++) {
      let slice = await runAgentSlice({ sandboxId, station, sessionId: `${runId}-${round}`, prompt, dev });
      while (!slice.done) {
        slice = await runAgentSlice({ sandboxId, station, sessionId: `${runId}-${round}`, continuation: slice.continuation, dev });
      }
      if (!template.verify) break;
      verify = await runVerify(sandboxId, template.verify); // the orchestrator checks; it doesn't trust the agent
      if (verify.ok) break;
      prompt = `The verification command \`${template.verify}\` failed. Output (tail):\n\n\`\`\`\n${verify.output}\n\`\`\`\n\nFix the code, run it again, and push. Update .factory/result.json.`;
    }

    const result = await readResult(sandboxId);
    const message = `${name === 'spec' ? 'docs(specs)' : 'feat'}: ${issueData.title} (#${issue})\n\nGenerated by the software factory (${runId}).`;

    if (dev) {
      // Dev already pushed; push whatever it left. Whether the PR may be marked ready is the rules' call.
      const { headSha } = await finishDevBranch(sandboxId, station, dev, message);
      await upsertPr(name, issue, branch, issueData.title, result, verify);
      const ready = await readyForReview(station, dev.pr, { verifyPassed: verify?.ok ?? false, changedSomething: headSha !== baseSha });
      if (!ready.ready) await blocked(`Implementation is blocked: ${ready.why}. See draft PR #${dev.pr}.`);
      return;
    }

    const changes = await readChanges(sandboxId);
    if (changes.length === 0) return await blocked(`The spec station finished without changing any file.\n\n${result.summary ?? ''}`);
    const commit = await commitStationChanges(station, { branch, baseSha, message, changes });
    if (!commit.committed) return await blocked(`Spec is blocked: ${commit.why}.`);
    const pr = await upsertPr(name, issue, branch, issueData.title, result);
    await comment(issue, `Specs are ready for review in #${pr}. A maintainer applies \`${config.labels.readyToImplement}\` to start the implementation.`);
  } finally {
    if (sandboxId) await stopSandbox(sandboxId);
    await setLabels(issue, [], [config.labels.running]);
  }
}
